spring:
  application:
    name: dolbomi

  datasource:
    hikari:
      # 이부분은 본인 경로로 변경하셔야 됩니다
      jdbc-url:  jdbc:h2:tcp://localhost/file:/Users/easymook/KH_Final_Project/back/tdb
      driver-class-name: org.h2.Driver
      username: sa
      password: 1234
  h2:
    console:
      enabled: true
      path: /h2-console
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

server:
  port: 8555

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true